mysqldata:
  image: mysql
  command: true

mysql:
  image: mysql
  volumes_from:
    - mysqldata
  environment:
    MYSQL_ROOT_PASSWORD: myrootpassword
    MYSQL_DATABASE: huginn
    MYSQL_USER: huginn
    MYSQL_PASSWORD: myhuginnpassword

huginn:
  build: .
  ports:
    - 5000:5000
  environment:
    HUGINN_DATABASE_NAME: huginn
    HUGINN_DATABASE_USERNAME: root
    HUGINN_DATABASE_PASSWORD: myrootpassword
    INTENTIONALLY_SLEEP: 10
    #DATABASE_INITIAL_CONNECT_MAX_RETRIES: 5
    PORT: 5000
  links:
    - mysql

